Fixed integration tests and added 2.2 compatibility
Checkmk/ansible-collection-checkmk.general pull request #347
Opened 2023-06-01 12:59 UTC by Max-checkmk

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- Integration-Tests just seem to run against 2.1 and 2.2, but all 3 sites are created as 2.0
- contact_group, host_group and service_group modules don't work with 2.2
- Integration test for the downtimes-module fails against 2.1 and 2.2 as services (cpu load, memory, ...) aren't found

## What is the new behavior?

- The prep.yml is looped now completely so every site gets created with the installed version from the task before.
- All _group modules have been fixed to work with 2.2
- Changed service description in the downtimes test to existing ones.

## Other information

Fix for _group-modules is not very pretty, but modules should be migrated to new API with version-check anyway.

2023-06-13 15:02 UTC, robin-checkmk requested changes

2023-06-13 15:02 UTC, robin-checkmk commented on tests/integration/targets/rule/tasks/prep.yml
> -  run_once: true  # noqa run-once[task]
This cannot be removed. It is necessary for the test to work properly.

2023-06-14 04:32 UTC, lgetwan reviewed
Thanks for fixing this!
I'm not sure if you can solve the comment I added in the code without depending on #344, too much.

2023-06-14 04:32 UTC, lgetwan commented on plugins/modules/contact_group.py
> +                ]
It would be nicer if you could use the getversion() method that you have introduced in #344

2023-06-14 07:06 UTC, Max-checkmk commented on plugins/modules/contact_group.py
> +                ]
Yes, but i would prefer to do this when migrating the whole plugin to the new API.

2023-06-14 10:56 UTC, lgetwan commented on plugins/modules/contact_group.py
> +                ]
Sounds reasonable.

2023-06-14 10:57 UTC, lgetwan approved these changes
Approved.

2023-06-14 13:36 UTC, merged