Fix module folder for future checkmk releases
Checkmk/ansible-collection-checkmk.general pull request #404
Opened 2023-08-07 08:49 UTC by msekania

Fixes issue #389 

## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently all three options *attributes*, *remove_attributes*, and *update_attributes* can be used simultaneously, which is no longer supported by API for Check MK >= v2.2.0p7

Issue Number: #389 

## What is the new behavior?

- issue a warning message if more then one option from *attributes*, *remove_attributes*, and *update_attributes* is used simultaneously for Check MK  < v2.2.0p7 
- fail with error message if more then one option from *attributes*, *remove_attributes*, and *update_attributes* is used simultaneously for Check MK  >= v2.2.0p7 

## Other information

2023-08-07 08:52 UTC, robin-checkmk commented
@msekania thanks for tackling this!
Is your branch up-to-date with our `devel`? Looks like there are some unrelated changes in here.

2023-08-07 08:57 UTC, msekania commented
> Is your branch up-to-date with our `devel`? Looks like there are some unrelated changes in here.

apparently not, changes should be only in folder.py

2023-08-07 09:48 UTC, robin-checkmk commented
I'll take a look at the failing tests and the weirdness with the additional changes.

2023-08-07 09:57 UTC, msekania commented
@robin-checkmk 

thanks!

2023-08-07 10:34 UTC, robin-checkmk commented
I understand the issue with the integration tests now but the solution is not trivial.
I will update this comment, once I have news.

2023-08-08 05:45 UTC, robin-checkmk commented
@msekania I implemented a hotfix for the integration tests, but the actual fix is already in `devel`.
So the current test findings should be valid, and if you pull the `devel` branch into yours, the integration tests should be fixed properly.

2023-08-08 06:40 UTC, lgetwan requested changes
Looks fine! Thanks for your contribution.
I just added one comment that you should solve before we merge this.

2023-08-08 06:40 UTC, lgetwan commented on plugins/modules/folder.py
> +            version_ge_220p7 = True
Can you put this into a separate function to keep the run_module() function a bit shorter?
BTW: This algorithm will not work for daily build versions, but I won't consider this a show stopper. ;-)

2023-08-08 15:19 UTC, msekania commented
@robin-checkmk,

I pulled devel branch, and merged it in the current, which required rebase.

2023-08-08 15:58 UTC, robin-checkmk commented
@msekania I am uncertain what exactly happened, but I think your idea of creating a new and clean PR ist the best approach. Go ahead and create it, I will merge tomorrow then and release.
Thanks!

2023-08-08 16:16 UTC, closed without merging