New time period module
Checkmk/ansible-collection-checkmk.general pull request #426
Opened 2023-08-25 09:24 UTC by Max-checkmk

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

There is no module for time periods

## What is the new behavior?

- Added a module for creating, updating and deleting time periods

## Other information

2023-08-25 12:16 UTC, lgetwan requested changes
The documentation could be a bit more detailed. Probably, you could use the tasks from your integration test.

I tested the module with some use cases:
- When creating a timeperiod that already exists, a failure is shown (should be "OK").
- When updating a timeperiod without any actual change, the result is "changed" (should be "OK").
- When adding an exclude time range, this isn't visible in the UI.
- When deleting a timeperiod that doesn't exist, a failure is shown (should be "OK").

Here's the playbook i used:
```---

# Make sure to keep the tests in sync!
# Rather use the tests than this playbook directly.

- name: "Test timeperiods"
  hosts: all
  gather_facts: 'no'
  vars_files:
    - ./vars/config.yml

  tasks:
  - name: create timeperiod
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "lunch"
      alias: "Mahlzeit"
      active_time_ranges: [
              { 
                  "day": "all",
                  "time_ranges": [
                      {
                          "start": "12:00",
                          "end": "13:00"
                      }
                  ]
              }
          ]
      state: present
    delegate_to: localhost
    run_once: 'yes'

  # fails. should be "OK"
  - name: create timeperiod again
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "lunch"
      alias: "Mahlzeit"
      active_time_ranges: [
              { 
                  "day": "all",
                  "time_ranges": [
                      {
                          "start": "12:00",
                          "end": "13:00"
                      }
                  ]
              }
          ]
      state: present
    delegate_to: localhost
    run_once: 'yes'

  - name: create timeperiod that uses the first one
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "working_hours"
      alias: "Ballern"
      active_time_ranges: [
              { 
                  "day": "all",
                  "time_ranges": [
                      {
                          "start": "8:00",
                          "end": "17:00"
                      }
                  ]
              },
          ]
      exclude: ["Mahlzeit"]
      state: present
    delegate_to: localhost
    run_once: 'yes'

  - name: update timeperiod
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "working_hours"
      active_time_ranges: [
              { 
                  "day": "all",
                  "time_ranges": [
                      {
                          "start": "9:00",
                          "end": "18:00"
                      }
                  ]
              },
          ]
      state: present
    delegate_to: localhost
    run_once: 'yes'

  # fails. should be "OK"
  - name: update timeperiod. again.
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "working_hours"
      active_time_ranges: [
              { 
                  "day": "all",
                  "time_ranges": [
                      {
                          "start": "9:00",
                          "end": "18:00"
                      }
                  ]
              },
          ]
      state: present
    delegate_to: localhost
    run_once: 'yes'

  - name: remove used timeperiod
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "lunch"
      state: absent
    delegate_to: localhost
    run_once: 'yes'
    ignore_errors: true

  - name: remove timeperiod
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "working_hours"
      state: absent
    delegate_to: localhost
    run_once: 'yes'

  # fails. should be "OK"
  - name: remove timeperiod again
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "working_hours"
      state: absent
    delegate_to: localhost
    run_once: 'yes'

  - name: remove used timeperiod
    checkmk.general.timeperiod:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      name: "lunch"
      state: absent
    delegate_to: localhost
    run_once: 'yes'
```

2023-08-25 13:59 UTC, Max-checkmk commented
> The documentation could be a bit more detailed. Probably, you could use the tasks from your integration test.
> 
> I tested the module with some use cases:
> 
>     * When creating a timeperiod that already exists, a failure is shown (should be "OK").
> 
>     * When updating a timeperiod without any actual change, the result is "changed" (should be "OK").
> 
>     * When adding an exclude time range, this isn't visible in the UI.
> 
>     * When deleting a timeperiod that doesn't exist, a failure is shown (should be "OK").
> 
> 
> ```

Hi Lars,

thanks for the feedback. I had a dumb mistake in it, which is now corrected.
And i forgot to finish the examples, which is also done now.

Please try it again.
What i didn't change is the error which is thrown, if someones tries to delete something what doesn't exist.
Not sure about this...

Nice weekend! ;)

2023-08-25 14:42 UTC, msekania commented
> What i didn't change is the error which is thrown, if someones tries to delete something what doesn't exist.
> Not sure about this...

@Max-checkmk,

`state: absent` means that it's not there, that means that someone does not try to delete something but rather to ensure that it's not there, hence no error.

2023-08-25 15:05 UTC, lgetwan requested changes

2023-08-25 15:05 UTC, lgetwan commented on plugins/modules/timeperiod.py
> +            timeperiodupdate.headers["If-Match"] = result.etag
An Update should only be done in the case the mentioned parameters are different in the already existing Timeperiod. 
Otherwise running the same playbook again and again will always do a change in the environment. You have to avoid this.

2023-08-25 15:05 UTC, lgetwan commented
Nice weekent y'all!

2023-08-28 08:24 UTC, Max-checkmk commented
> `state: absent` means that it's not there, that means that someone does not try to delete something but rather to ensure that it's not there, hence no error, rather no change. And changed if it was there and deleted.

You're right. I just had a look at some other modules and as far i see at the moment we're not really consistent for all modules here. ;)
I will do the change for this module with the next commit!

2023-08-28 09:49 UTC, Max-checkmk commented on plugins/modules/timeperiod.py
> +            timeperiodupdate.headers["If-Match"] = result.etag
Nice idea, but this will need a lot of time to accomplish.

So as example we want to update a time period for all weekdays with these time ranges:
`active_time_ranges: '[{"day": "all", "time_ranges": [{"start": "08:00:00", "end": "17:00:00"}]}]'`

And we try to compare this with the existing time ranges of a time period, we get this:
`[{'day': 'monday', 'time_ranges': [{'start': '08:00', 'end': '17:00'}]}, {'day': 'tuesday', 'time_ranges': [{'start': '08:00', 'end': '17:00'}]}, {'day': 'wednesday', 'time_ranges': [{'start': '08:00', 'end': '17:00'}]}, {'day': 'thursday', 'time_ranges': [{'start': '08:00', 'end': '17:00'}]}, {'day': 'friday', 'time_ranges': [{'start': '08:00', 'end': '17:00'}]}, {'day': 'saturday', 'time_ranges': [{'start': '08:00', 'end': '17:00'}]}, {'day': 'sunday', 'time_ranges': [{'start': '08:00', 'end': '17:00'}]}]`

So we would need to adjust
- the given time ranges to every single day of the week
- remove the seconds from the input, as internally there are no seconds (in contrast to the API Docs example...)

We redirect the raw data to the API so at first you would have to convert the data to something you can work with in python.

2023-08-29 06:32 UTC, lgetwan commented on plugins/modules/timeperiod.py
> +            timeperiodupdate.headers["If-Match"] = result.etag
I see, that's too complex.

But what do you think of this as an intermediate solution:
If the data provided by the task is completely equal with the current data from the API, we don't change anything. But if the task e.g. has seconds in the data, and the API has not, we do post a change to the API.

Many users are running their playbooks daily or hourly, and that would help them a lot, already.

2023-08-30 12:02 UTC, Max-checkmk commented on plugins/modules/timeperiod.py
> +            timeperiodupdate.headers["If-Match"] = result.etag
Please have a look at my last commit. Now there is a rudimentary comparison between existing and new values.
Based on that we could add the other checks (full week and seconds) sometime.

2023-08-31 15:04 UTC, lgetwan approved these changes
Works as described. :-)

2023-10-16 09:38 UTC, robin-checkmk commented
@Max-checkmk please check the failing sanity check and fix it. I think we had this issue with the host or folder module in the past. Maybe @lgetwan can help here.

2023-10-16 09:43 UTC, Max-checkmk commented
> @Max-checkmk please check the failing sanity check and fix it. I think we had this issue with the host or folder module in the past. Maybe @lgetwan can help here.

Well, the problem seems to be inside the folder-module and not in this module. As far as i can read the logs from the test...

2023-10-16 10:25 UTC, robin-checkmk commented
True. Then we will ignore the failing test here and fix it in `devel` directly.

2023-10-16 10:31 UTC, merged