Add "customer" parameter in module and request
Checkmk/ansible-collection-checkmk.general pull request #427
Opened 2023-08-25 09:51 UTC by muehlings

Adds the neccessary parameter "customer" to the corresponding CME API endpoints in the ansible modules.

- user.py
- host_group.py

## Pull request type
Please check the type of change your PR introduces:

- [x] Feature

## What is the current behavior?
Issue Number: `#65`

## What is the new behavior?

- Make ansible modules ready for Checkmk CME API endpoints.

TODO:

- Identify all modules who need the "customer" parameter.
- Modify the POST/PUT logic? I think the other Checkmk versions will fail at requests with additional parameters.
- Problems with host.py in 2.2.0p8 CEE detected (API endpoint change which prevents ipaddress+alias+tags?)
- Problems with auth_type in user API endpoint? Wrong default when not set?

2023-08-30 12:04 UTC, muehlings commented
A default to `customer: "provider"` will not work, because the extra field "customer" is not supported in non-CME environments.
I tried to add the logic in the module: 
![grafik](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/80385927/373708cf-7d42-490f-b80f-4e07baed3436)

My playbook decides wether the parameter should be given to the module:
![grafik](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/80385927/db7f99f3-e986-43c5-a12b-90d04a4d331e)

Then the only thing you need to pay attention to is the inventory. For non-CME site don't add the customer in the vars. I'm not using the bulk methods. I use dictionaries and then loop over the items.

A new approach could be the lookup module for version. Then we can look up it the parameter is neccessary or not.

2023-09-07 14:56 UTC, robin-checkmk commented
@muehlings you are correct and to me your code looks sensible. A review pending I am good with the solution. Once that is sorted out, I will take care of the roles and such, which need updates as well. Just like you pointed out, when it comes to the inventory.

2023-09-07 15:03 UTC, robin-checkmk commented on plugins/modules/user.py
> +        auth_type=dict(type="str", choices=["password", "automation"], required=True),
Two questions: Did this ever work? And was there a (implicit) default value?
The reason for the questions: This could be a breaking change, if it worked before without specifying the `auth_type`.

2023-09-08 07:16 UTC, muehlings commented on plugins/modules/user.py
> +        auth_type=dict(type="str", choices=["password", "automation"], required=True),
I did not explicitly supply the auth_type and the customer was created, because the API endpoint does not require the auth_type. The user gets created and the change-password-task tells me that the user was changed.
```
TASK [Create a user.] ***
ok: [SMUE] => (item=testuser)

TASK [Set user password.] ***
changed: [SMUE] => (item=testuser)
```
The user is created with the right authentication method but is not usable, because the password could not be set:
![grafik](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/80385927/8ded3be9-ceac-4aa6-af14-8715bf911343)
So there seems to be no implicit default.

See documentation (2.2.0p7 CME):
![grafik](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/80385927/71404dc2-b454-4816-8666-394f483ee312)
Required: username, fullname, customer

There a several options:
- Modify the API endpoint and make "auth_type" a required parameter (because the user is not fully created or usable, even if you supplied a password) [but then the module requires at least that Checkmk version]
- Workaround in the module as i did (make auth_type a required field even if the endpoint does not enforce it)
- Combination of both: Use the workaround now and wait for the changes in the endpoint. Then the workaround becomes obsolete in the future. Perhaps we should add the failsafe default 'password' in the module as this should be the normal behavior an enduser would expect. [this should be the preferred option]

2023-09-08 11:04 UTC, robin-checkmk commented on plugins/modules/user.py
> +        auth_type=dict(type="str", choices=["password", "automation"], required=True),
I might be missing something, but we could also go for a default value of `password`, right? The bug only requires, that we provide an `auth_type`, right?

We should find a solution that works as stable as possible and potentially avoid current or future bugs here.

But I also think it can be sensible to make the `auth_type` a required parameter.

Maybe a brief voting by reacting to this comment (ping @lgetwan @Max-checkmk):
:tada: means: Default to `password` and do not make `auth_type` required.
:rocket:  means: Make `auth_type` required.

P.S.: @muehlings can you look at the integration tests for the user module in the meantime? I added the `auth_type` to some tests and now they fail hard. But I do not understand the failure.

2023-09-08 12:06 UTC, muehlings commented on plugins/modules/user.py
> +        auth_type=dict(type="str", choices=["password", "automation"], required=True),
Just a guess:
User.from_module(module.params) wants to return params["state"] but params has no key "state" to return.
Should be line 487 in user.py:
`    desired_user = User.from_module(module.params)`
wants to return
`        return cls(params["name"], state=params["state"], attributes=attributes)`

I currently have no idea how to debug at my side, because I don't see this error.

2023-09-25 11:36 UTC, muehlings commented on plugins/modules/user.py
> +        auth_type=dict(type="str", choices=["password", "automation"], required=True),
I think I left the auth_type as it is (for the tests). 
I'm successfully running the integration test for the user module atm:
![grafik](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/80385927/20b593d6-8374-4e5b-b645-3aed10bb383c)
I'm setting the customer variable when it is neccessary and omit it in case of CRE, CFE, CEE.

The YAML wasn't intuitive. I set
```
- name: "{{ outer_item.version }} - Unset customer when needed."
  set_fact:
    customer: null
  when: outer_item.edition == "cre"
```
and had to check for "None"
`customer: "{{ (customer != None ) | ternary(customer,omit) }}"`
and under the hood "null" was "" (empty string).

I tested all easier approaches like `customer: {{customer|default(omit)}}` but all these variants failed, because setting `customer: null` 
set 
`customer: ""` 
instead of unsetting the variable. 

I think I will need some more time to publish it.

2023-10-23 10:45 UTC, robin-checkmk requested changes

2023-10-23 10:45 UTC, robin-checkmk commented on tests/integration/targets/user/vars/main.yml
> +server_url: "https://maas.pdv-systeme.de/"
You probably do not want to set your internal domain as a default. :)

2023-10-23 10:45 UTC, robin-checkmk commented on tests/integration/targets/user/vars/main.yml
> +download_user: "hotline@pdv-systeme.de"
This looks like a company-specific user.

2023-10-23 10:45 UTC, robin-checkmk commented on plugins/modules/password.py
> +        type: str
Is there a reason, that this description differs from the description for the other modules?
Maybe go with the following sentence for all modules?
`When using the Checkmk Managed Edition you need to specify which customer this object belongs to.`

2023-10-23 12:10 UTC, robin-checkmk commented on plugins/modules/user.py
> +        auth_type=dict(type="str", choices=["password", "automation"], required=True),
Did you also try something like this?
`{% if customer is defined and customer | length %}customer{% else %}""{% endif %}`?
Anyway, I am uncertain, if I really understand the problem.

Let me try to summarize:

- A user is not using the CME and omits the `customer` attribute: All good.
- A user is not using the CME but provides the `customer` attribute: Ugly crash in Checkmk. We should catch that in the module.
- A user is using the CME and omits the `customer` attribute: Expected error.
- A user is using the CME and provides the `customer` attribute: All good.

If those assumptions are correct, then I am uncertain if we even need the logic you implemented in the tests. We could simply use two blocks. One tests the CME with the `customer` attribute, one tests the others without the attribute. That way, we do not need to implement magic in the tests. Because the level of convenience you are aiming for here, would make sense in a role, that should be ready to use. But in the tests, we are in control of what happens.

TL;DR: I feel like we are good with the current behavior regarding the `customer` attribute. I can take care of the tests for you. And I would add some documentation, so the expected input is clear. Does that make sense to you @muehlings?

Also, we should catch the second scenario and print a nice message like "You tried to pass the `customer` attribute to a non-CME site. Please review the documentation." or so.

2023-10-23 15:27 UTC, robin-checkmk commented on tests/integration/targets/user/vars/main.yml
> +download_user: "hotline@pdv-systeme.de"
I cleaned it up, as I needed the proper value for the tests to work on GitHub.

2023-11-06 10:44 UTC, muehlings commented on plugins/modules/user.py
> +        auth_type=dict(type="str", choices=["password", "automation"], required=True),
Hello Robin!
Answer to TL;DR: Everything ok from my side. Please fix the tests and documentation if neccessary.

2023-11-06 16:52 UTC, robin-checkmk approved these changes

2023-11-06 16:53 UTC, robin-checkmk commented
@lgetwan or @Max-checkmk can one of you take a look at the code and give a second opinion about this change please? Thanks!

2023-11-08 16:24 UTC, merged