feat: add no log capability for agent role
Checkmk/ansible-collection-checkmk.general pull request #456
Opened 2023-10-24 19:16 UTC by S0obi

## Pull request type
- [X] Feature

## What is the current behavior?

Resolves: #452

## What is the new behavior?

Introduce `checkmk_agent_no_log` variable to better protect the automation password to be logged in system logs.

2023-10-24 19:18 UTC, S0obi commented
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

2023-10-24 19:18 UTC, S0obi commented
recheck

2023-10-25 15:35 UTC, robin-checkmk requested changes
What do you think about adding your logic to the server role as well?
I like the style, how you implemented things, so if you are up to it, go right ahead.

2023-10-25 15:35 UTC, robin-checkmk commented on roles/agent/defaults/main.yml
> +checkmk_agent_no_log: 'false'
I think we should actually go for a default of `true`, as I would want a "security by default" approach here.
Ideally one does not need the output of those commands most of the time.

2023-10-25 15:36 UTC, robin-checkmk commented on roles/agent/README.md
> +The value of the `no_log` attribute. Set to `true` for enhanced password security.
We should also maybe clarify a little more, what happens here. You and I get it, but for the more inexperienced users, I would like to put this in simple terms.

2023-10-25 18:10 UTC, S0obi commented on roles/agent/defaults/main.yml
> +checkmk_agent_no_log: 'false'
Ok, I am glad if we follow this approach, I will do my best to improve the documentation to help users especially regarding troubleshooting.

2023-10-26 07:21 UTC, robin-checkmk commented on roles/agent/README.md
> +Whether to log sensitive information like passwords, Ansible output will be censored for enhanced security by default. Set to `false` for easier troubleshooting. Be carreful when changing this value
Just a typo left: "carreful" should be "careful". :)

2023-10-26 07:22 UTC, robin-checkmk commented on roles/agent/defaults/main.yml
> +checkmk_agent_no_log: 'false'
I was just thinking to align the configurability. So both roles behave the same. If you do not want to implement it here, I will gladly do so myself at a later time. No pressure. :)

2023-10-26 18:15 UTC, S0obi commented on roles/agent/defaults/main.yml
> +checkmk_agent_no_log: 'false'
I introduced a new `checkmk_server_no_log` variable to align the behavior between agent and server roles. I also took the opportunity to fix the server role README that was messed up, most probably due to a failed copy & paste 👀

2023-10-27 07:15 UTC, robin-checkmk commented on changelogs/fragments/no_log.yml
> +  - Avoid logging passwords by default for extra security
Last nitpick: Please write the changelog like this:
- Agent role - Avoid logging passwords by default for extra security
- Server role - Avoid logging passwords by default for extra security
While it seems redundant, after compilation the context is important.

2023-10-27 07:15 UTC, robin-checkmk commented on roles/agent/defaults/main.yml
> +checkmk_agent_no_log: 'false'
Looking good, thanks!

2023-10-27 07:16 UTC, robin-checkmk commented on changelogs/fragments/no_log.yml
> +  - Avoid logging passwords by default for extra security
And while you are at it: Fix the missing newline the tests complain about and then we are ready for merge. :)

2023-10-27 07:30 UTC, S0obi commented on changelogs/fragments/no_log.yml
> +  - Avoid logging passwords by default for extra security
Fixed 🎉

2023-10-27 10:12 UTC, S0obi commented on changelogs/fragments/no_log.yml
> +  - Avoid logging passwords by default for extra security
Fixed another new line missing and that failed the pipeline

2023-10-27 10:26 UTC, robin-checkmk approved these changes
Looks good! Pending the tests, this PR will be merged for the next release.

2023-11-02 15:36 UTC, merged