Added errorhandling to lookup API
Checkmk/ansible-collection-checkmk.general pull request #475
Opened 2023-11-13 16:04 UTC by Max-checkmk

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- If there's an error when calling the url, the error is passed uncontrolled to the user

## What is the new behavior?

- Errors when calling the endpoint will be catched in the lookup_api and returned to the lookup-modules for output

## Other information

I'm sure there's a nicer way to do this. So any improvements appreciated.
Main problem is that ansible doesn't allow using the ansible.errors library in the api folder, just inside the modules.

2023-11-14 10:39 UTC, lgetwan requested changes
I appreciate a lot to have a logging mechanism! :-D
Only minor change requests below...

2023-11-14 10:39 UTC, lgetwan commented on plugins/module_utils/lookup_api.py
> +            response = to_text(raw_response.read())
Actually, it would be nicer to directly do a return here:
`return to_text(raw_response.read())`

2023-11-14 10:39 UTC, lgetwan commented on plugins/module_utils/lookup_api.py
> +                response = json.dumps(
Do a return here, too. 
And in the following cases, as well.
Then, we get completely rid of the variable "response".

2023-11-15 14:24 UTC, Max-checkmk commented on plugins/lookup/folder.py
> +                    % (response["url"], response["code"], response["msg"])
You're right, even when i always use all 3 values in the lookup_api.
Changed with last commit!

2023-11-15 14:24 UTC, Max-checkmk commented on plugins/module_utils/lookup_api.py
> +            response = to_text(raw_response.read())
Accepted and committed.

2023-11-16 12:27 UTC, lgetwan approved these changes
Looks perfect, now!

2023-12-01 12:00 UTC, merged