Extend the functionality of the folder module
Checkmk/ansible-collection-checkmk.general pull request #539
Opened 2024-01-27 20:38 UTC by msekania

Extends the functionality of the folder module.
See also #533 .

## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #533 

## What is the new behavior?

- One can supply a) a list o strings or b) dict as a romote_attributes parameter. 
- a) reproduces the functionality of the REST API, and was already implemented
- b) removes the specified attribute if the given folder had such an attribute.

## Other information

2024-02-09 09:10 UTC, lgetwan requested changes
Thanks a lot for improving the functionality of this module! It looks like you invested quite a bit of Hirnschmalz. :-)
Unfortunately, the diff shown here is not the diff between [feature/migrate_folder_module](https://github.com/Checkmk/ansible-collection-checkmk.general/tree/feature/migrate_folder_module) and [feature/extend_folder_module_functionality](https://github.com/msekania/ansible-collection-tribe29.checkmk/tree/feature/extend_folder_module_functionality), but agains the devel branch. So I did my own diff on the commandl ine. ;-)
I added some comments, but nothing severe.

2024-02-09 09:10 UTC, lgetwan commented on plugins/modules/folder.py
> +        current_attributes = self.current.get("attributes", {})
AFAIK, I added this line. But after thinking about it again, it's a bit risky, as if we change the values of _current_attributes_, this will also change the values in `self.current["attributes"]`.
A bit further down, you added
`(tmp_remove, tmp_rest) = (current_attributes, {})`
which extends this to _tmp_remove_. If we change this variable, it will also change the self.current["attributes"].
For some reason, it works anyway, maybe, because `self.current["attributes"]` is no longer used after the `_detect_changes()` finished its work.
Still, I think, we should do a proper copying of the dict, as the name "_detect_changes()" doesn't sound like it changes data.
What do you think about that?

2024-02-09 09:10 UTC, lgetwan commented on plugins/modules/folder.py
> +        description: The state of your folder.
This looks like a cut&paste mistake.

2024-02-09 09:10 UTC, lgetwan commented on plugins/modules/folder.py
> +            elif isinstance(tmp_remove_attributes, dict):
I didn't get completely what you coded here, but I tested it, and it does what is expected. :-)

2024-02-09 09:10 UTC, lgetwan commented on plugins/modules/folder.py
> +        if data.get("remove_attributes"):
Oops. Thanks for changing this from "remove_attribute" to "remove_attributes". :-)

2024-02-09 10:13 UTC, msekania commented
> Thanks a lot for improving the functionality of this module! It looks like you invested quite a bit of Hirnschmalz. :-) Unfortunately, the diff shown here is not the diff between [feature/migrate_folder_module](https://github.com/Checkmk/ansible-collection-checkmk.general/tree/feature/migrate_folder_module) and [feature/extend_folder_module_functionality](https://github.com/msekania/ansible-collection-tribe29.checkmk/tree/feature/extend_folder_module_functionality), but agains the devel branch. So I did my own diff on the commandl ine. ;-) I added some comments, but nothing severe.

@lgetwan 
I do not know what went wrong here, but header says

[msekania](https://github.com/msekania) wants to merge 10 commits into [Checkmk:feature/migrate_folder_module](https://github.com/Checkmk/ansible-collection-checkmk.general/tree/feature/migrate_folder_module) from [msekania:feature/extend_folder_module_functionality](https://github.com/msekania/ansible-collection-tribe29.checkmk/tree/feature/extend_folder_module_functionality)

and `Resolve conflicts` shows also something different than branch changes :man_shrugging:

2024-02-09 10:15 UTC, msekania commented on plugins/modules/folder.py
> +                    value.pop("meta_data")
Done!

2024-02-09 10:19 UTC, msekania commented on plugins/modules/folder.py
> +        current_attributes = self.current.get("attributes", {})
I'll keep it as it is for the moment, 
I want to check if the logic stays sound if we start to modify this.
In fact user can also supply empty dict as a parameter, like
`attributes: {}`

2024-02-09 10:19 UTC, msekania commented on plugins/modules/folder.py
> +        description: The state of your folder.
Yes, Thanks!
I made corresponding changes

2024-02-09 10:22 UTC, msekania commented on plugins/modules/folder.py
> +            elif isinstance(tmp_remove_attributes, dict):
yes, it looks a bit complicated, unfortunately I have not have a clearer version for the moment.

2024-02-09 12:15 UTC, lgetwan approved these changes

2024-02-09 15:19 UTC, lgetwan commented
For some reason, the integration test that checks idempotency, fails in the 2nd step of these two:
```
- name: "{{ outer_item.version }} - {{ outer_item.edition | upper }} - Update folder attributes without specifying title (name)."
  folder:
    server_url: "{{ checkmk_var_server_url }}"
    site: "{{ outer_item.site }}"
    automation_user: "{{ checkmk_var_automation_user }}"
    automation_secret: "{{ checkmk_var_automation_secret }}"
    path: "{{ checkmk_folder_attr_test.path }}"
    state: "present"
    update_attributes:
      tag_criticality: "test"
      tag_networking: "wan"
  delegate_to: localhost
  run_once: true  # noqa run-once[task]

- name: "{{ outer_item.version }} - {{ outer_item.edition | upper }} - Check the idempotency of Update attributes."
  folder:
    server_url: "{{ checkmk_var_server_url }}"
    site: "{{ outer_item.site }}"
    automation_user: "{{ checkmk_var_automation_user }}"
    automation_secret: "{{ checkmk_var_automation_secret }}"
    path: "{{ checkmk_folder_attr_test.path }}"
    update_attributes:
      tag_criticality: "test"
    state: "present"
  delegate_to: localhost
  run_once: true  # noqa run-once[task]
  register: test_output
  failed_when: test_output.changed | bool
```
The forst task returns:
```
"msg": "200 - Folder modified. Changed: update attributes: {\"tag_criticality\": \"test\", \"tag_networking\": \"wan\"}"
```
The second one returns:
```
 "msg": "200 - Folder modified. Changed: attributes"
```

2024-02-09 15:48 UTC, msekania commented
might be related to the fact that `attribute` is {}.

I have to check it.

2024-02-09 16:01 UTC, msekania commented
> For some reason, the integration test that checks idempotency, fails in the 2nd step of these two:

I found the issues, line 307,
In essence I have introduced when I "simplified" if statement.
Sorry

2024-02-13 12:06 UTC, lgetwan commented
Thanks for fixing this, Michael!
Then, the PR is ready to be merged. :-)

2024-02-13 23:36 UTC, merged