Add files via upload
Checkmk/ansible-collection-checkmk.general pull request #541
Opened 2024-01-30 15:22 UTC by muehlings

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

There is no module for creating, editing or deleting site connections (Setup->Distributed Monitoring).

## What is the new behavior?

[Draft] Module for creating, editing or deleting site connections .

## Other information

Second try of generating Ansible modules from OpenAPI definition for Checkmk. This code is 99% generated from the checkmk.yaml file in SwaggerUI. Manually changed parts are around the [...] brackets. Module is based on Checkmk 2.2.0p20-CME YAML.

2024-01-30 15:35 UTC, muehlings commented
Playbook:
```
  - name: "Create site_connection '{{item.site_config.basic_settings.site_id}}'"
    checkmk.general.site_connection:
      "automation_secret": "{{automation_secret}}"
      "automation_user": "{{automation_user}}"
      "server_url": "{{server_url}}"
      "site": "{{site}}"
      "state": "{{item.state}}"

      "site_config": "{{item.site_config}}"
      "secret": "{{item.secret|default(omit)}}"

    loop: "{{ site_connections|flatten(levels=1) }}"
    loop_control:
      label: "{{ item.site_config.basic_settings.site_id }}"
```

host_vars:
```
---
site_connections:
- site_config:
    basic_settings:
      alias: First site
      customer: provider
      site_id: Site
    configuration_connection:
      direct_login_to_web_gui_allowed: true
      disable_remote_configuration: true
      enable_replication: true
      replicate_event_console: true
      replicate_extensions: true
      ignore_tls_errors: false
      url_of_remote_site: http://1.2.3.4/Site/check_mk/
      user_sync:
        sync_with_ldap_connections: all
    status_connection:
      connect_timeout: 2
      connection:
        encrypted: true
        host: 127.0.0.1
        port: 6559
        socket_type: tcp
        verify: false
      disable_in_status_gui: false
      persistent_connection: false
      proxy:
        global_settings: false
        params:
          cache: true
          channel_timeout: 3.8
          channels: 15
          connect_retry: 4.6
          heartbeat:
            interval: 12
            timeout: 3.5
          query_timeout: 120.5
        tcp:
          only_from:
          - 192.168.1.1
          port: 6560
          tls: false
        use_livestatus_daemon: with_proxy
      status_host:
        status_host_set: disabled
      url_prefix: /Site/
  state: present
  secret: NO_SECRET_HERE
```

2024-02-05 22:37 UTC, robin-checkmk requested changes

2024-02-05 22:37 UTC, robin-checkmk commented on plugins/modules/site_connection.py
> +    [...]
Documentation is a must-have. Please align the documentation section with existing modules and the `options` section with the `module_args`.

2024-02-05 22:37 UTC, robin-checkmk commented on plugins/modules/site_connection.py
> +    [...]
These examples are unusable. Please make them user-friendly.

2024-04-14 04:00 UTC, closed without merging