[Draft] Add module aux_tag
Checkmk/ansible-collection-checkmk.general pull request #542
Opened 2024-01-30 15:25 UTC by muehlings

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

There is no module for creating, editing or deleting aux tags.

## What is the new behavior?

[Draft] Module for creating, editing or deleting aux tags.

## Other information

Third try of generating Ansible modules from OpenAPI definition for Checkmk. This code is 99% generated from the checkmk.yaml file in SwaggerUI. Manually changed parts are around the [...] brackets. Module is based on Checkmk 2.2.0p20-CME YAML. Now with a class for the managed object/endpoint.

2024-01-30 15:37 UTC, muehlings commented
Playbook:
```
  - name: "Create aux_tag '{{item.aux_tag_id}}'"
    checkmk.general.aux_tag:
      "automation_secret": "{{automation_secret}}"
      "automation_user": "{{automation_user}}"
      "server_url": "{{server_url}}"
      "site": "{{site}}"
      "state": "{{item.state}}"

      "aux_tag_id": "{{item.aux_tag_id}}"
      "title": "{{item.title}}"
      "topic": "{{item.topic}}"
      "help": "{{item.help|default(omit)}}"

    loop: "{{ aux_tags|flatten(levels=1) }}"
    loop_control:
      label: "{{ item.aux_tag_id }}"
```

host_vars:
```
---
aux_tags:
- help: 'Hosts with Windows operating system'
  aux_tag_id: windows
  state: present
  title: Windows hosts
  topic: Operating systems
- help: 'Hosts with Linux operating system'
  aux_tag_id: linux
  state: present
  title: Linux hosts
  topic: Operating systems
- help: 'Dummy'
  aux_tag_id: dummy
  state: absent
  title: Dummy tag for create/delete
  topic: Dummy
```

2024-02-05 22:37 UTC, robin-checkmk requested changes

2024-02-05 22:37 UTC, robin-checkmk commented on plugins/modules/aux_tag.py
> +    [...]
Please provide at least some basic examples.

2024-02-05 22:37 UTC, robin-checkmk commented on plugins/modules/aux_tag.py
> +    [...]
Documentation is a must-have. Please align the documentation section with existing modules and the `options` section with the `module_args`.

2024-04-14 04:00 UTC, closed without merging