Migrate Rule module to new API
Checkmk/ansible-collection-checkmk.general pull request #572
Opened 2024-02-22 16:22 UTC by lgetwan

I migrated the rule module to the new API and made it a bit nicer.
Will update this description soon. Just wanted to save my work before the weekend. ;-)

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Rule module is a bit ugly and only ~23% idempotent.

## What is the new behavior?

Rule module
- is nicer,
- uses the new API,
- is ~87% idempotent.
- The rules lookup module accepts filtering for folders, now.

## Other information

100% idempotency will be reached, once the value_raw is handled differently by Checkmk and its REST API.

2024-03-22 14:57 UTC, lgetwan commented
@msekania: You already spent a lot of time diving into the rule module and its flaws. Can you have a look at my completely rewritten rule module and test it, if you have some time?

2024-03-22 17:01 UTC, msekania commented
@lgetwan, yes I'll do 

> @msekania: You already spent a lot of time diving into the rule module and its flaws. Can you have a look at my completely rewritten rule module and test it, if you have some time?

2024-03-22 18:43 UTC, robin-checkmk commented on tests/integration/targets/rule/tasks/test.yml
> +    var: created_rules
Was this only for testing, or should it stay to better understand subsequent issues?

2024-03-22 18:43 UTC, robin-checkmk commented on tests/integration/targets/rule/vars/main.yml
> -        }"
Why do we remove this rule set? Because of the breaking change in Checkmk 2.3?
Should we replace it or migrate it?

2024-03-24 15:34 UTC, msekania commented
@lgetwan,

I've gone through the code and have more than a few suggestions for improvement and cleanup. I'll do the code review comments right after.

As for the rest, overwriting, it's good overall, but I don't like that the functionality has been reduced compared to the existing version. Namely, the check whether a rule already exists no longer takes place if rule_id is not specified. I understand that the existing version was not perfect in this regard, but it was still useful and all my use cases relied on this functionality. Currently there is also no way to compensate the "removed" functionality with the lookup rule plugin.

I am currently working to bring that functionality back, if you do not mind.

2024-03-24 16:15 UTC, msekania requested changes
I cannot make any changes to this branch otherwise I could apply the changes directly or via merge request

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +                if not desired["rule"].get(what, {}).get(key):
should read
```
                if not desired["rule"].get(what).get(key):
```
`get(what, {})`    `{}` is not required see lines 473-474

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
remove extra clean line

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
add
```
        state = "absent"
```

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +            self.state = "present"
change with
```
            state = "present"
```

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +                    current["rule"][key] = value
more compact version
```
            current["rule"] = {key: value for key, value in extensions.items() if key in CURRENT_RULE_KEYS}
```

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +        return current
change this three lines with
```
        return (current, state)
```

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +                and location.get("position", "") == "bottom"
if default values then may be the right ones
```
                location.get("folder", "/") == "/"
                and location.get("position", "bottom") == "bottom"
```

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +        pos = location.get("position", "")
If default values, may be the right ones?
```
        pos = location.get("position", "bottom")
```

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
just for the guide
```
        # else:
        #     # cannot happen
```

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +        data = self.desired.get("rule", {}).copy()
should read
```
        data = self.desired.get("rule").copy()
```
rule is required parameter

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +            self.module.fail_json(msg="ERROR: The parameter value_raw is mandatory.")
```
            self.module.fail_json(msg="ERROR: The parameter value_raw is mandatory when 'state is present'.")
```
IMHO, better message

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +            m = self._merge_results({"created": create_result, "moved": move_result})
not used not needed

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +            self.module.fail_json(msg="ERROR: The parameter value_raw is mandatory.")
```
            self.module.fail_json(msg="ERROR: The parameter value_raw is mandatory when 'state is present'.")
```
IMHO, better message

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +            return self._merge_results({"editd": edit_result, "moved": move_result})
spelling
`edited` instead of `editd`

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +                    # ],
uncomment!

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +        msg="Invalid parameters provided.",
```
        msg="",
```
fits better

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +            msg="Running in check mode. Would have done an %s" % mode,
```
            msg="Running in check mode. Would have %s" % mode,
```
IMHO, better message

2024-03-24 16:15 UTC, msekania commented on plugins/modules/rule.py
> +            changed=False,
```
            changed=True,
```
user should see in check-mode if changes would be carried out in the normal mode. follows Ansible beheviour

2024-03-24 16:42 UTC, msekania commented on plugins/modules/rule.py
```
        # when neighbour is specified, verify that it exists otherwise give warning
        neighbour_id = self.params.get("rule").get("location").get("neighbour", "")
        if neighbour_id != "":
            (neighbour, state) = self._get_rule_by_id(neighbour_id)

            if state == "absent":
                self.module.warn("Specified neighbour: '%s' does not exist" % neighbour_id)
            else:
                self.desired["location"]["folder"] = neighbour.get("location").get("folder")
```

2024-03-24 16:52 UTC, msekania commented on plugins/modules/rule.py
> +        desired_location = desired.get("rule", {}).get("location")
I think, this should read
```
        desired_location = desired.get("location")
```

2024-03-25 07:27 UTC, lgetwan commented
Hi @msekania 

Thanks a lot for your comprehensive review! 
I need some time to reply to the single findings though, as my calendar is currently packed with customer calls.

> As for the rest, overwriting, it's good overall, but I don't like that the functionality has been reduced compared to the existing version. Namely, the check whether a rule already exists no longer takes place if rule_id is not specified. I understand that the existing version was not perfect in this regard, but it was still useful and all my use cases relied on this functionality. Currently there is also no way to compensate the "removed" functionality with the lookup rule plugin.
> 
> I am currently working to bring that functionality back, if you do not mind.

I know that my changes are breaking existing stuff. I decided to do that, because the current module is kind of unreliable and unpredictable in its behavior, and so I wanted to move the module and its use cases to the direction of how the API is intended to be used. I will discuss with my colleagues if we might bring back the previous behavior at least as a side-feature.
Or probably (as you also wrote) it would help extending the rules lookup module, so it includes conditions and raw_value to search for. Would that be an option for you? If not, How should the rules lookup module behave, so you can keep your current use cases?

Best regards
Lars

2024-03-25 12:57 UTC, msekania commented
Hi @lgetwan,

General problem which I have with a new version (without modification) is that that one creates all the time the same rule, because there is no any mechanisms that allows to check and stop recreation of the same rule again and again.
Currently one requires to provide rule_id in order to compare, edit, or move the rule. This will stay as it is.

I would appreciate if one would have a mechanism to try to deduce the rule_id if user is not providing it from the rest of parameters. Positioning in folder issues one can solve by introducing extra position value "any" in addition to "top", "bottom", "before", and "after", which will ignore precise position check within folder in `is_equal` check,

I have finished implementation of this features, and it's more or less like what I would like to have. I also found some extra bugs in current version.

In which form I  should provide the changes?

Best regards,
Michael

2024-03-26 19:54 UTC, robin-checkmk commented
> In which form I should provide the changes?

@msekania may I suggest a branch based on this branch? That should allow you to open a PR onto this one.

2024-04-22 10:52 UTC, lgetwan commented on tests/integration/targets/rule/tasks/test.yml
> +    var: created_rules
Yes, that was only for testing. Removed it.

2024-04-22 10:56 UTC, lgetwan commented on plugins/modules/rule.py
> +        rule_id: "{{ response.content.id }}"
Thanks for fixing this in your PR, alredy.

2024-04-22 10:59 UTC, lgetwan commented on plugins/modules/rule.py
> +            k for k, v in self.rule_list.items() if v == self.folder
Thanks for fixing this in your PR, alredy.

2024-04-22 11:00 UTC, lgetwan commented on plugins/modules/rule.py
> +        return []
Thanks for fixing this in your PR, alredy.

2024-04-22 11:01 UTC, lgetwan commented on plugins/modules/rule.py
> +            return self._merge_results({"editd": edit_result, "moved": move_result})
Thanks for fixing this in your PR, alredy.

2024-04-22 11:03 UTC, lgetwan commented on plugins/modules/rule.py
> +                    # ],
Thanks for fixing this in your PR, alredy.

2024-04-22 11:03 UTC, lgetwan commented on plugins/modules/rule.py
> +        msg="Invalid parameters provided.",
Thanks for fixing this in your PR, alredy.

2024-04-22 11:03 UTC, lgetwan commented on plugins/modules/rule.py
> +            msg="Running in check mode. Would have done an %s" % mode,
Thanks for fixing this in your PR, alredy.

2024-04-22 11:04 UTC, lgetwan commented on plugins/modules/rule.py
> +            changed=False,
Thanks for fixing this in your PR, alredy.

2024-04-22 11:10 UTC, lgetwan commented on plugins/modules/rule.py
> +        desired_location = desired.get("rule", {}).get("location")
I don't think so. "location" is a parameter inside of the rule, not a top level one.

2024-04-22 11:17 UTC, lgetwan commented on tests/integration/targets/rule/vars/main.yml
> -        }"
I think, it's not a good idea to use rulesets in our tests that have different data structures from one (tested) Checkmk version to another.

2024-04-22 13:23 UTC, lgetwan commented
Again, it's complicated when modifying an existing rule (by providing an ID) to decide if conditions should be set or not. Querying the values of an existing rule and re-applying them leads to problems.

2024-04-22 13:27 UTC, msekania commented
> Again, it's complicated when modifying an existing rule (by providing an ID) to decide if conditions should be set or not. Querying the values of an existing rule and re-applying them leads to problems.

@lgetwan can you provide some examples

2024-04-26 18:36 UTC, robin-checkmk commented
My initial tests show, that both for Checkmk 2.2.0p25 and 2.3.0b6 the idempotent is still completely broken without specifying the `rule_id`.

Representative example rule definition:
```yaml
  - ruleset: "checkgroup_parameters:cpu_utilization_os"
    rule:
      location:
        folder: "/"
        position: "bottom"
      properties: {
        "comment": "Set by Ansible",
        "disabled": false
      }
      value_raw: "{'core_util_time': (100.0, 300, 900), 'core_util_time_total': (100.0, 300, 900)}"
      conditions:
        host_labels: []
        service_labels: []
        host_tags: []
```
Accompanying task:
```yaml
- name: "Create Rules."
  checkmk.general.rule:
    server_url: "{{ server_url }}"
    site: "{{ site }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    ruleset: "{{ item.ruleset }}"
    rule: "{{ item.rule }}"
    state: "present"
  loop: "{{ rules_global }}"
  delegate_to: localhost
  run_once: true  # noqa run-once[task]
```

I am still investigating and will update this post, if I find something else.

2024-04-29 10:11 UTC, msekania commented
Thanks @robin-checkmk, for the example,

I'll have some tests.

Concerning `rule_id`, problem is that it's not existing when rule is created, therefor it's useless in bare create task.
If `rule_id` will remain the only solution for the moment, then working example would be:
- search if the rule with desired properties already exists, and if yes get `rule_id`,
- incorporate `rule_id` if found in the task which creates rule, otherwise omit this filed entirely.

2024-04-29 10:21 UTC, msekania commented
@robin-checkmk, 

In current rue module setting any value in description lest say
```yml
  - ruleset: "checkgroup_parameters:cpu_utilization_os"
    rule:
      location:
        folder: "/"
        position: "bottom"
      properties: {
        "description": "test"
        "comment": "Set by Ansible",
        "disabled": false
      }
      value_raw: "{'core_util_time': (100.0, 300, 900), 'core_util_time_total': (100.0, 300, 900)}"
      conditions:
        host_labels: []
        service_labels: []
        host_tags: []
```

solves idempotency issues. I'll check new version next, but this point might be essential.

2024-04-29 12:13 UTC, msekania commented
@robin-checkmk, @lgetwan,

I have a fix for the problem, namely issue is `description` field in `properties` in `DESIRED_DEFAULTS` line 353 https://github.com/Checkmk/ansible-collection-checkmk.general/blob/39f143e456ccd2e40431830deb72c6b4843ca915/plugins/modules/rule.py#L353, may be also https://github.com/Checkmk/ansible-collection-checkmk.general/blob/39f143e456ccd2e40431830deb72c6b4843ca915/plugins/modules/rule.py#L365,
`description` should not be the part of `properties`  in `DESIRED_DEFAULTS` (at least for `pre_230`)

2024-05-01 19:29 UTC, robin-checkmk commented
> In current rue module setting any value in description let's say [...] solves the idempotency peoblem.
I can confirm this for 2.2. Setting `"description": "test"`, makes virtually all my example rules idempotent again. In 2.3 this seems not to help though.

> I have a fix for the problem, namely issue is description field in properties in DESIRED_DEFAULTS line 353 [...], may be also [365], description should not be the part of properties in DESIRED_DEFAULTS (at least for pre_230)
I pushed a change commenting out these lines. But I want @lgetwan to get a chance to verify, if this is a sensible fix before merging it.

2024-05-02 11:27 UTC, lgetwan commented
I will check that tomorrow.

2024-05-03 14:59 UTC, lgetwan commented
The last commit solves the problem for 2.2.0, but I still don't get why it doesn't work for 2.3.0...

2024-05-08 12:39 UTC, lgetwan commented
@robin-checkmk & @msekania,
That was a hard piece of work considering that the diff is quite small, but now I'm pretty sure, that the idempotency in 2.3.0 is as "good" as in 2.2.0. Can you run your tests, again, as well, please?

2024-05-08 13:33 UTC, msekania commented
@lgetwan,

there are some more improvements see #602 , I could not test 2.3.0 yet, but similar fixes might be due for 2.3.0 as well.

I also have a question concerning your last changes.
What if I intentionally provide empty list just to clean up already set one?
I think this changes should also go similar to what I have done for comment and description in #602

2024-05-08 15:28 UTC, msekania commented
@lgetwan, 

I have an Idea how to incorporate logic of your changes in what I wrote above. I'll need hour or two at most.
Of course you can drop them if you do not like them, no problem.

2024-05-08 16:30 UTC, msekania commented
@lgetwan 

> @lgetwan,
> 
> I have an Idea how to incorporate logic of your changes in what I wrote above. I'll need hour or two at most. Of course you can drop them if you do not like them, no problem.

DONE

2024-05-10 14:25 UTC, lgetwan commented
Ok, now idempotency looks quite good with 2.2.0 and 2.3.0, at least for my own tests and the integration tests.
Thanks again for #602, @msekania!
Can you run your tests against the newest version of this PR?

2024-05-23 21:48 UTC, robin-checkmk commented
I can confirm idempotency as well for 2.2 and 2.3.
The only hiccup is, that `"comment": "{{ ansible_date_time.iso8601 }} Set by Ansible"` will not work, as you always get a different comment. But I think that is fine. In that case one needs to use the `rule_id`.

The only challenges that remain from my point of view are:
1. Verify that the module documentation is up-to-date with the recent changes.
2. Decide whether this is a breaking change or not and how to release it.

2024-05-24 18:05 UTC, merged