Add condition to only run tasks when needed, closes #557
Checkmk/ansible-collection-checkmk.general pull request #579
Opened 2024-03-12 12:22 UTC by peterge1998

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: `#557 ` 

## What is the new behavior?

The tasks only run when the agent was installed or the host was created on the checkmk server

## Other information

2024-03-12 18:53 UTC, peterge1998 commented
recheck

2024-03-12 19:02 UTC, robin-checkmk requested changes

2024-03-12 19:07 UTC, robin-checkmk commented
> I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

The CLA Bot says, that you did not make your commits with an email associated with GitHub but also gives instructions how to fix it:

> Peter Gerhards seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2024-03-13 11:01 UTC, peterge1998 commented
> > I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.
> 
> The CLA Bot says, that you did not make your commits with an email associated with GitHub but also gives instructions how to fix it:
> 
> > Peter Gerhards seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

I cant because I registered another github account with that email address...

2024-03-13 11:05 UTC, peterge1998 commented on roles/agent/tasks/Linux.yml
> -  when: checkmk_agent_create_result.changed | bool
https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#changed

Because it is already a boolean... I prefer to not use duplicate code which does not add any benefit. But I can add `| bool` again if this is a deal breaker for you

2024-03-13 18:24 UTC, robin-checkmk commented
> I cant because I registered another github account with that email address already...

Can you use that account to sign the CLA here? It is a one time thing, you do not need to do it with every new PR.

2024-03-14 06:28 UTC, peterge-misoft commented
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

2024-03-14 06:29 UTC, peterge-misoft commented
recheck

2024-03-14 11:40 UTC, robin-checkmk commented on roles/agent/tasks/Linux.yml
> -  when: checkmk_agent_create_result.changed | bool
That is actually a good point, because while a user could overwrite the content of the variable with anything, it is more than unlikely that they will actually do so. I will do some research on the matter, but if in doubt, I see no problem in dropping it here.

2024-03-14 12:55 UTC, robin-checkmk commented
@peterge1998 we are looking into the CLA issue in the backchannel and I will update you as soon as I can.

We can work on your PR nevertheless for the time being.

If you look at the tests, you cannot the the actual error, but I ran the tests locally with debugging enabled and this is roughly the error:
```yaml
fatal: [centos8]: FAILED! => {"msg": "The conditional check 'checkmk_agent_create_result.changed or checkmk_install_agent_result.changed' failed. The error was: error while evaluating conditional (checkmk_agent_create_result.changed or checkmk_install_agent_result.changed): 'checkmk_install_agent_result' is undefined\n\nThe error appears to be in '/home/vagrant/ansible_collections/checkmk/general/roles/agent/tasks/Linux.yml': line 80, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"{{ ansible_system }}: Check for Agent Updater Binary.\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```
You are using a variable, that is undefined in certain cases, and you need to handle that.

2024-03-15 09:10 UTC, peterge1998 commented
> You are using a variable, that is undefined in certain cases, and you need to handle that.

I added is defined checks to check if my variable is defined before checking if the result has failed. Missed that, but sure, if the task that registers the variable is not executed at all i cant check if it is changed later.

2024-03-15 16:21 UTC, englertor commented
recheck

2024-03-15 19:22 UTC, peterge1998 commented
recheck

2024-04-01 16:16 UTC, robin-checkmk commented on roles/agent/tasks/main.yml
> +    or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
This breaks the existing logic. Even worse, it circumvents a configuration variable on which users rely.
So `or` does not work, as the first condition needs to make the whole condition `false`, if itself is `false`.
Your addition would probably need to be `and` connected, while the two parts of it need to stay `or` connected.

2024-04-02 07:54 UTC, peterge1998 commented on roles/agent/tasks/Linux.yml
> +        or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
And what if I register `checkmk_agent_updater_binary` when both variables, which i would like to introduce, are not defined in another task to get it populated?
This would help line 105 and 122, since those lines only check if `checkmk_agent_updater_binary` exists.

2024-04-02 07:54 UTC, peterge1998 commented on roles/agent/tasks/Linux.yml
> +        or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
And what if I register `checkmk_agent_updater_binary` when both variables, which i would like to introduce, are not defined in another task to get it populated?
This would help line 105 and 122, since those lines only check if `checkmk_agent_updater_binary` exists.

2024-04-02 08:02 UTC, peterge1998 commented on roles/agent/tasks/Linux.yml
> +        or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
Done

2024-04-02 08:22 UTC, peterge-misoft commented on roles/agent/tasks/Linux.yml
> +    or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
This way should be fine:
```
    checkmk_agent_edition | lower != "cre"
    and checkmk_agent_updater_binary.stat.exists | bool
    and checkmk_agent_update | bool
    and (checkmk_agent_pass is defined and checkmk_agent_pass | length)
    and (checkmk_agent_secret is not defined)
    and
    (
        (checkmk_agent_create_result is defined and checkmk_agent_create_result.changed)
        or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
    )
```

2024-04-02 08:22 UTC, peterge-misoft commented on roles/agent/tasks/Linux.yml
> +    or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
See other comment

2024-04-02 08:23 UTC, peterge-misoft commented on roles/agent/tasks/Linux.yml
> +    or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
See other comment

2024-04-02 08:23 UTC, peterge-misoft commented on roles/agent/tasks/Linux.yml
> +    or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
See other comment

2024-04-02 08:23 UTC, peterge-misoft commented on roles/agent/tasks/Linux.yml
> +    or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
See other comment

2024-04-02 08:25 UTC, peterge-misoft commented on roles/agent/tasks/main.yml
> +    or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
See other comment

2024-04-04 21:17 UTC, robin-checkmk commented on roles/agent/tasks/Linux.yml
> +        or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
See, this is the issue I see with this approach: We make things way more complicated and harder to understand. And only for cosmetic reasons. There is no technical reason to change the current behavior.

The only solution is this part of the code would be to make it never change with something like `changed_when: false`. But I really do not like this suppression mechanism.

2024-04-04 21:17 UTC, robin-checkmk commented on roles/agent/tasks/Linux.yml
> +        or (checkmk_install_agent_result is defined and checkmk_install_agent_result.changed)
See, this is the issue I see with this approach: We make things way more complicated and harder to understand. And only for cosmetic reasons. There is no technical reason to change the current behavior.

The only solution is this part of the code would be to make it never change with something like `changed_when: false`. But I really do not like this suppression mechanism.

2024-04-05 08:15 UTC, closed without merging