Folder lookup module - Update and improve the examples.
Checkmk/ansible-collection-checkmk.general pull request #607
Opened 2024-05-29 12:50 UTC by lgetwan

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

The examples in the module aren't up-to-date.

## What is the new behavior?

- The examples respect the new dictionary structure
- There's an example on how to query multiple folders, which results in a list of dictionaries.

2024-05-29 20:07 UTC, robin-checkmk requested changes

2024-05-29 20:07 UTC, robin-checkmk commented on changelogs/fragments/lookup_folder_examples.yml
> +  - Folder lookup module - Update and improve the examples.
The original changelog fragment said `Return the complete folder information, not only the extensions.`. I think this here is misleading, as it says, what you did in this PR, but we actually want to explain here, what is the breaking change and how to update their configuration. Maybe you have a good idea, otherwise I can propose something. We should also update the existing fragment, rather than adding a new one.

2024-05-29 20:07 UTC, robin-checkmk commented on plugins/lookup/folder.py
> +    msg: "Extended attributes of folder /network: {{ attributes.extensions }}"
Is this the only thing that we need to communicate to users?
"Update `{{ attributes }}` to `{{ attributes.extensions }}` and you are good to go"? :slightly_smiling_face:

2024-06-03 06:50 UTC, lgetwan commented on plugins/lookup/folder.py
> +    msg: "Extended attributes of folder /network: {{ attributes.extensions }}"
Yes, more or less, that's what makes this change _breaking_. It's a rather soft break. ;-)
Previously, the module returned the green part, now it returns the blue part:
![image](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/80964943/a4b06a73-c56b-4e52-a7cf-b5139659b8d4)

2024-06-03 06:57 UTC, lgetwan commented on changelogs/fragments/lookup_folder_examples.yml
> +  - Folder lookup module - Update and improve the examples.
I tried to improve the changelog.

2024-06-03 18:08 UTC, robin-checkmk approved these changes
Looking good, ready to merge!

2024-06-03 18:08 UTC, robin-checkmk commented on plugins/lookup/folder.py
> +    msg: "Extended attributes of folder /network: {{ attributes.extensions }}"
Great, thanks for confirming and updating the changelog!

2024-06-03 19:22 UTC, merged