Taggroup update 2.4
Checkmk/ansible-collection-checkmk.general pull request #640
Opened 2024-07-17 14:24 UTC by Max-checkmk

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- When creating or updating a taggroup we use the parameter "ident".
-> Issue Number: #547 

## What is the new behavior?

- With Werk 16364 we added the parameter "id". Beginning with 2.4.0 "ident" will be removed, so this plugin uses "id" if the version is 2.4 or higher.

## Other information
Added version check in the module and also made 1 class out of the 4 which existed before.

2024-07-18 13:39 UTC, robin-checkmk commented
Fix confirmed, pending code review we are good to release this. :partying_face:

2024-07-30 07:28 UTC, lgetwan requested changes
Looks like you did some nice cleanup work, as well. :-)
I suggested minor changes. They are only cosmetics but would complete the cleanup.

2024-07-30 07:28 UTC, lgetwan commented on plugins/modules/tag_group.py
> +                data["id"] = self.params.get("name")
To me, this looks like it could be part of the "normalize_data()" function, as well.

2024-07-30 07:28 UTC, lgetwan commented on plugins/modules/tag_group.py
> +                taggroup.headers["If-Match"] = taggroup.current.etag
I would pot this line into the put() method, as well.

2024-07-30 07:28 UTC, lgetwan commented on plugins/modules/tag_group.py
> +def normalize_data(raw_data, ver):
This could become a method of the TaggroupAPI class. Then, it would also have instant access to self.ver and self.data.

2024-07-30 07:28 UTC, lgetwan commented on plugins/modules/tag_group.py
>                  msg="Taggroup doesn't exist.",
"Taggroup already absent." would explain the state a bit better.

2024-07-31 12:35 UTC, Max-checkmk commented on plugins/modules/tag_group.py
> +                data["id"] = self.params.get("name")
I wouldn't integrate this into the function, as this is only needed when creating a new taggroup

2024-07-31 12:39 UTC, Max-checkmk commented on plugins/modules/tag_group.py
> +                taggroup.headers["If-Match"] = taggroup.current.etag
Line for the If-Match header is now in the method!

2024-07-31 12:39 UTC, Max-checkmk commented on plugins/modules/tag_group.py
>                  msg="Taggroup doesn't exist.",
Changed

2024-07-31 12:39 UTC, Max-checkmk commented on plugins/modules/tag_group.py
> +def normalize_data(raw_data, ver):
Done!

2024-08-01 14:06 UTC, lgetwan approved these changes
Passt!

2024-08-01 14:08 UTC, merged