Implement module "site_management" for configuring distributed monitoring
Checkmk/ansible-collection-checkmk.general pull request #654
Opened 2024-08-20 13:27 UTC by lgetwan

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

There was no module for managing distributed monitoring sites.

## What is the new behavior?

Now there is.

## Other information

Thanks to the usage of IDs in the site management, it was possible to make this module idempotent. If you run into problems, please let us know.

2024-08-21 06:26 UTC, robin-checkmk reviewed
Can we discuss the module name?
The UI calls it "Distributed monitoring", but the REST API "Site Management".
My issue here is, that the latter sounds **a lot** like what our `server` role does.
We also follow the UI in other places IIRC, as the REST API made some interesting naming choices.

2024-08-21 07:51 UTC, lgetwan commented
I also disliked the module name tbo, so I changed it to _distmon_, which is short and recognizable. 
Also removed Python Typing to make it Python2.7 compatible.
Changelog was also added lately.

2024-08-22 14:44 UTC, robin-checkmk requested changes
I am getting the overall feeling, that it might make sense, to abstract the module more from the REST API. The structure of the module could probably be flatter than that of the API. That is not to say, that this is not a good first version, we just might want to keep it in mind for a later review.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                        remote_username:
I think just `user` would suffice, right? We explain, that the user needs admin privileges in the description anyway. And it should be obvious, that this user has to be from the remote site.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                        remote_password:
I think just `password` would suffice, right?

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                login_data:
Nitpick: Maybe `authentication`?

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                        socket_type:
Maybe just `type`? Looking at the structure it would be `site_config.status_connection.connection.type`. I think that is clear enough.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                proxy:
Maybe this should actually be `liveproxy`, just to avoid confusion?

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                        use_livestatus_daemon:
I am not happy with this bulky option. Maybe we abstract this like `enabled` with the values `true` and `false`, resulting in `with_proxy` and `direct` respectively. Not sure if that makes enough sense, but feels cleaner.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                persistent_connection:
`persistent` should suffice.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                            default: disabled
Shouldn't we be able to determine this from the provided values? No values mean `disabled`, values for `host` and `site` mean, it is enabled. Or am I missing something here?

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                disable_in_status_gui:
Maybe `disable` is good enough here, as the details are in the description.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                enable_replication:
Just `replication`.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                url_of_remote_site:
Just `url`.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                direct_login_to_web_gui_allowed:
Maybe `login_to_web_gui`?

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                replicate_event_console:
Just `event_console`.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                replicate_extensions:
Just `extensions`.

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                - remote site for configuring Checkmk.
This seems to be REST API specific, at least I cannot find it in the UI. Do we even need this here?

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                    type: str
This seems redundant as we already have a `site_id` higher up, but it is probably technically not possible to merge them, right?

2024-08-22 14:44 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                    default: http://localhost/nonexistant/check_mk/
Do we set this intentionally to an unlikely hostname, or could we also go with a nicer name?

2024-08-26 12:15 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                    default: http://localhost/nonexistant/check_mk/
Actually, we should open an internal ticket to fix this behavior of the REST API. I hope, they fix this quickly, so I suggest to just keep this "nonexistant" site.

2024-08-27 06:40 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                    type: str
That makes sense. Then let's stick with approach 1 for the initial version, and we will see, what the feedback looks like. We can still do an iteration, if we learn, that the current approach does not work for users.

2024-08-27 06:40 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                    default: http://localhost/nonexistant/check_mk/
"we" as in you will, or "we" as in I should do it? :wink:

2024-08-27 08:56 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                    default: http://localhost/nonexistant/check_mk/
Done.

2024-08-27 09:15 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                        remote_password:
Done.

2024-08-27 09:17 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                        remote_username:
Changing it to "username" was easier (because then, it's the same field name as used in the REST API).

2024-08-27 09:17 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                proxy:
I will stick with the field name used by the REST API (see other comments).

2024-08-27 09:17 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                replicate_extensions:
I will stick with the field name used by the REST API (see other comments).

2024-08-27 09:18 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                replicate_event_console:
I will stick with the field name used by the REST API (see other comments).

2024-08-27 09:22 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                - remote site for configuring Checkmk.
When doing a GET and then using the data gathered with a POST, this field should be used. Otherwise the central site will no longer be logged in to that remote site.
Maybe, this parameter is not needed, yet. But once, we provide a lookup module, it should be there. So, I suggest to keep it.

2024-08-27 09:31 UTC, robin-checkmk commented on plugins/doc_fragments/distmon_options.py
> +                                - remote site for configuring Checkmk.
Maybe we can extend the documentation a little then? With what you just wrote it makes sense, while before I did not get the full picture.

2024-08-27 10:46 UTC, lgetwan commented
Currently, the integration tests are not correct. I have to refine them. But from my point of view, the module itself is ready for some first manual tests.

2024-08-28 06:11 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                - remote site for configuring Checkmk.
To be honest, I didn't find a (currently supported) use-case that included setting this secret. Thus, I removed the parameter. The module only uses the secret internally to determine if Checkmk is logged in to a remote site.

2024-08-28 06:13 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                direct_login_to_web_gui_allowed:
I will stick with the field name used by the REST API (see other comments).

2024-08-28 06:13 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                enable_replication:
I will stick with the field name used by the REST API (see other comments).

2024-08-28 06:13 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                disable_in_status_gui:
I will stick with the field name used by the REST API (see other comments).

2024-08-28 06:15 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                            default: disabled
I will stick with the way the REST API handles this (see other comments).
Unfortunately, "status_host_set" is a mandatory field, even with config replication turned off.

2024-08-28 06:15 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                persistent_connection:
I will stick with the field name used by the REST API (see other comments).

2024-08-28 06:15 UTC, lgetwan commented on plugins/doc_fragments/distmon_options.py
> +                                        use_livestatus_daemon:
I will stick with the field name used by the REST API (see other comments).

2024-08-28 06:26 UTC, lgetwan commented
Looks like the integration tests runs into this problem: https://github.com/actions/runner-images/issues/6680
Probably, the tests take too long?

2024-08-28 08:48 UTC, robin-checkmk commented
> Looks like the integration tests runs into this problem: [actions/runner-images#6680](https://github.com/actions/runner-images/issues/6680) Probably, the tests take too long?

I'll investigate, but I doubt, it is a timeout issue, we have/had tests, which run longer. It might be resource exhaustion.

2024-08-28 14:20 UTC, lgetwan commented
It was indeed resource exhaustion. I reduced the number of remote sites to be created. Now github is happy.

2024-09-05 10:32 UTC, robin-checkmk approved these changes
I am happy with the changes. Pending a code review, we are good to merge.

2024-09-24 09:42 UTC, robin-checkmk commented on changelogs/fragments/site.yml
> +    Refer to the module documentation for further details.
I just realized, that we should document, that this module cannot accept the remote site's livestatus certificate.
At least in the changelog under "known_issues", but probably a note in the module documentation itself might make sense.

2024-09-24 11:27 UTC, robin-checkmk commented on changelogs/fragments/site.yml
> +    Refer to the module documentation for further details.
I added a hint, let me know, what you think.

2024-09-24 11:29 UTC, robin-checkmk commented
The linting failures are irrelevant to this PR. I will fix them in the `devel` branch.

2024-09-25 09:59 UTC, lgetwan commented on changelogs/fragments/site.yml
> +    Refer to the module documentation for further details.
That's an important advise for the user. Good idea.

2024-09-30 07:52 UTC, mike1098 commented
I tested the following without issues against 2.2.0p33cee:

- Creating a site connection
- Loging in to a site
- Changing an attribute of a site connection
- Logout from a site
- Remove a site

Will discuss with my colleague as soon as he is back from vacation but I would say its working good.
Thank you for all the effort spent.

2024-10-09 06:39 UTC, merged