Implementing inventory plugin for the Checkmk collection
Checkmk/ansible-collection-checkmk.general pull request #656
Opened 2024-09-06 12:15 UTC by Max-checkmk

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- It's not possible to use Checkmk as source for an ansible inventory

## What is the new behavior?

- This PR introduces the first version of the inventory plugin

## Other information

This first version of the plugin has the possibility to get tags and sites as groups.
Please comment or open an issue if you have suggestions for enhancements or ideas for future extensions of this plugin.

2024-09-09 12:43 UTC, lgetwan commented
I already did some tests. :-) 
Will continue tomorrow.

2024-09-10 14:58 UTC, lgetwan commented on plugins/inventory/checkmk.py
> +"""
Is it possible to extend the example to make it clear that calling
```
ansible-inventory -i inventory/checkmk.yml --list     # or
ansible-inventory -i inventory/checkmk.yml --list -vvvv
```
is the thing to do? I had a hard time figuring out that the way I called the command was correct, but it failed because of some misconfiguration in my site. To me, it looked like the inventory plugin wasn't used at all. Calling it with "-vvvv" would have shown me that it actually _is_ used.

2024-09-11 11:33 UTC, robin-checkmk requested changes

2024-09-11 11:33 UTC, robin-checkmk commented on .github/workflows/ans-unit-test-inventory.yaml
> +#   cancel-in-progress: true
This can be enabled.

2024-09-11 11:33 UTC, robin-checkmk commented on plugins/inventory/checkmk.py
> +            default: True
Did you try to use `extends_documentation_fragment: [checkmk.general.common]` like in the normal modules here? I know it does not work for lookup plugins, but maybe for inventories?

2024-09-11 11:33 UTC, robin-checkmk commented on plugins/inventory/checkmk.py
> +"""
I am also missing the explanation, how to exactly use the plugin, or is that documented elsewhere?

2024-09-11 11:33 UTC, robin-checkmk commented on tests/unit/plugins/inventory/conftest.py
> +fake_lookupapi = importlib.import_module(
Maybe we want to use the term "mock" here (and probably elsewhere), to make clear, what is happening here?

2024-09-19 11:25 UTC, Max-checkmk commented on changelogs/fragments/checkmk.yml
> +  - Inventory module - Added module for creating an dynamic inventory with Checkmk as source.
Done

2024-09-19 11:39 UTC, Max-checkmk commented on .github/workflows/ans-unit-test-inventory.yaml
> +#   cancel-in-progress: true
Enabled and already gone through the test

2024-09-19 11:48 UTC, Max-checkmk commented on tests/unit/plugins/inventory/conftest.py
> +fake_lookupapi = importlib.import_module(
I think both words match and at least other unit tests (docker inventory as example) use "fake_api" too.
But i wouldn't care if we decide to change it here.

2024-09-23 06:27 UTC, robin-checkmk commented on tests/unit/plugins/inventory/conftest.py
> +fake_lookupapi = importlib.import_module(
I can live with it, especially, if others do it the same way. :+1:

2024-09-23 08:50 UTC, robin-checkmk commented on plugins/inventory/checkmk.py
> +        groupsources:
When not declaring this option, we get an error `argument of type 'NoneType' is not iterable`.
Can we define a default value of e.g., `site` in the plugin, so users get at least some output and do not assume something is broken entirely? Especially, as this is marked as `required: false`. Or we need to make it required.

2024-09-23 08:50 UTC, robin-checkmk commented on plugins/inventory/checkmk.py
> +            description: Name of the plugin. Should always be C(checkmk.general.checkmk)
The naming looks odd, but I assume others do is the same way as well? IIRC Amazon uses e.g., `ec2` as the plugin name. Should we consider something like `checkmk.general.hosts`? That would even enable us to create inventory plugins for other elements at some point. Just a thought.

2024-09-23 08:50 UTC, robin-checkmk commented on plugins/inventory/checkmk.py
> +"""
I updated the EXAMPLES. What do you guys think, does that make enough sense?

2024-09-23 08:50 UTC, robin-checkmk commented on plugins/inventory/checkmk.py
> +            default: True
I implemented this and nothing complains, so I think we are good.

2024-09-27 09:15 UTC, lgetwan commented on plugins/inventory/checkmk.py
> +"""
Yes, that's exactly the part that I was missing.

2024-09-30 07:46 UTC, Max-checkmk commented on plugins/inventory/checkmk.py
> +        groupsources:
Just added a check for that.

2024-09-30 08:29 UTC, Max-checkmk commented on plugins/inventory/checkmk.py
> +            description: Name of the plugin. Should always be C(checkmk.general.checkmk)
Like just discussed, we stay on checkmk.

2024-09-30 08:41 UTC, robin-checkmk approved these changes

2024-09-30 08:42 UTC, lgetwan approved these changes

2024-09-30 08:48 UTC, merged