Clean up and standardize variables in tests
Checkmk/ansible-collection-checkmk.general pull request #671
Opened 2024-10-10 16:09 UTC by robin-checkmk

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: `e.g. #1` 

## What is the new behavior?

-
-
-

## Other information

2024-10-16 08:35 UTC, robin-checkmk commented
@msekania I cannot expect this from you and I don't. But if you can spare a few minutes, I appreciate any and every pair of eyes, that double-checks, if I broke testing logic or if I missed something. But a "no" to this request is more than fine. :)

2024-10-16 08:55 UTC, msekania commented
@robin-checkmk, yes sure, no problem.
I'll have a look late today if it's fine

2024-10-16 10:00 UTC, msekania reviewed
After just visual code reviewing.

2024-10-16 10:06 UTC, robin-checkmk commented on CONTRIBUTING.md
> +[Ansible Unit Tests](https://docs.ansible.com/ansible/latest/dev_guide/testing_unit.html) run unit tests created by the maintainers of the respective modules, to ensure the code works as intended. Th
Dang it, there is an `s` missing: https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html

I will fix it.

2024-10-16 10:08 UTC, robin-checkmk commented on tests/integration/targets/downtime/tasks/test.yml
> +  failed_when: __checkmk_var_result_delete.changed == False
I like it, done!

2024-10-16 10:09 UTC, robin-checkmk commented on tests/integration/targets/user/tasks/test.yml
> +  failed_when: __checkmk_var_result_users_redelete-changed
At some point refactoring stuff, you just overlook stupid typos like this. Thanks for catching it!

2024-10-16 10:13 UTC, robin-checkmk commented on tests/integration/targets/contact_group/tasks/test.yml
> +    customer: "{{ (checkmk_var_customer != None) | ternary(checkmk_var_customer, omit) }}"  # See PR #427
We had a discussion [here](https://github.com/Checkmk/ansible-collection-checkmk.general/pull/427#discussion_r1335762098), and I still do not really understand, why the approach you suggest did not work, but I remember to have seen it myself. We can give it another try though, to see, if the issue is still there.

2024-10-16 10:26 UTC, msekania commented on tests/integration/targets/contact_group/tasks/test.yml
> +    customer: "{{ (checkmk_var_customer != None) | ternary(checkmk_var_customer, omit) }}"  # See PR #427
OK, I see the issues.
Then it should stay as it is.

2024-10-16 19:12 UTC, msekania requested changes
@robin-checkmk I think that's it

2024-10-17 07:02 UTC, robin-checkmk commented on tests/integration/targets/lookup_sites/tasks/test.yml
> +      msg: "{{ __checkmk_var_sites }}"
Fun fact: `ansible-lint` does not care about this, as long as the indentation is consistent. I fixed it anyways, thanks!

2024-10-17 07:07 UTC, robin-checkmk commented on tests/integration/targets/lookup_rules/tasks/test.yml
> +  loop: "{{ __checkmk_var_cpu_load_ruleset.__checkmk_var_one_ruleset }}"
It took me way to long to understand how to actually fix this, as after my initial refactoring it did not work anymore.
The problem is, that `rules` here was just the name of the registered variable in line `27`.
As that name is changed as well, we need to update it here accordingly.

Or did you see something, I did not see?

2024-10-17 07:19 UTC, msekania commented on tests/integration/targets/lookup_rules/tasks/test.yml
> +  loop: "{{ __checkmk_var_cpu_load_ruleset.__checkmk_var_one_ruleset }}"
@robin-checkmk 
`.__checkmk_var_one_ruleset`  ->  `.rules`

2024-10-17 07:21 UTC, msekania commented on tests/integration/targets/lookup_rules/tasks/test.yml
> +  loop: "{{ __checkmk_var_cpu_load_ruleset.__checkmk_var_one_ruleset }}"
@robin-checkmk
OK, I see now

2024-10-17 12:47 UTC, lgetwan approved these changes
Only did a rough scan-through, but looks good to me!

2024-10-17 12:53 UTC, merged