docs: clarify params server_url & site
Checkmk/ansible-collection-checkmk.general pull request #706
Opened 2024-12-31 21:00 UTC by HarisDotParis

This PR clarifies docs that the parameters `server_url` & `site` are being concatenated for all API requests and that `site` is meant NOT to be part of the parameter `server_url`. This PR might be (un)related to #684.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently the docs don't specify that `server_url` must NOT contain the site appendix/directory as its part. This leads at least in my case to long troubleshootings of the modules with the error lying in this misunderstand. The creator @jgotteswinter of issue #684 might have also suffered from this docs shortcomming.

## What is the new behavior?

Docs are adjusted slightly to mention the parameters being concatenated and that `server_url` shall not contain the `site` value.

## Other information

2024-12-31 21:05 UTC, HarisDotParis commented
recheck

2024-12-31 21:05 UTC, HarisDotParis commented
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

2025-01-02 10:46 UTC, robin-checkmk requested changes

2025-01-02 10:46 UTC, robin-checkmk commented on plugins/doc_fragments/common.py
> +            description: The base url of your Checkmk server including the protocol but excluding the site directory.
I would use 'site name' instead of 'site directory'.

2025-01-02 10:46 UTC, robin-checkmk commented on plugins/doc_fragments/common.py
> +            description: The site directory you want to connect to. This will be appended to the server_url as part of the API request url.
As above: 'directory' is not the correct terminology.

2025-01-02 14:54 UTC, HarisDotParis commented on plugins/doc_fragments/common.py
> +            description: The base url of your Checkmk server including the protocol but excluding the site directory.
I chose the word directory as the site is a directory of the URL path. If you don't agree with that word, I would rather omit any such word and just say `site` to avoid confusion. Which way do you prefer?

2025-01-06 10:29 UTC, robin-checkmk approved these changes

2025-01-06 10:30 UTC, merged